name: Deploy web server to Digital Ocean

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        # https://github.com/docker/login-action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        # https://github.com/docker/build-push-action
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-server:latest

      - name: SSH to Digital Ocean droplet and deploy
        uses: appleboy/ssh-action@master
        # https://github.com/appleboy/ssh-action
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITIAL_OCEAN_SSH_KEY }}
          fingerprint: ${{ secrets.DIGITAL_OCEAN_FINGERPRINT }}
          script: |
            docker pull web-server:latest
            docker stop web-server || true
            docker rm web-server || true
            docker run -d --name web-server -p 80:80 web-server:latest -e MONEY_MANAGER_ADDRESS=${{ secrets.MONEY_MANAGER_ADDRESS }} -e PERSONAL_WEBSITE_ADDRESS={{ secrets.PERSONAL_WEBSITE_ADDRESS }} web-server
